services:
  jora:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://jora-mysql-db:3306/joradb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      API_REDIS_HOST: jora-redis-db
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
      - mongo
      - redis

  mysql:
    image: mysql:8.0
    container_name: jora-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: joradb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    container_name: jora-mongo-db
    restart: always
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: jora-redis-db
    restart: always
    volumes:
      - ./redisdata:/data

volumes:
  mongo_data:
  mysql_data: