spring:
  application:
    name: Jora
  freemarker:
    expose-request-attributes: true
  mvc:
    static-path-pattern: /static/**
  datasource:
    generate-unique-name: false
    url: jdbc:mysql://jora-mysql-db:3306/joradb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
  data:
    mongodb:
      host: jora-mongo-db
      database: joradb
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cache:
    redis:
      time-to-live: 900000 #ttl 15 min
  kafka:
    bootstrap-servers: kafka:9092,172.17.0.1:9092,localhost:9092

server:
  address: 0.0.0.0
  port: 8081

logging:
  level:
    root: INFO
    org.mongodb.driver: WARN
    com.mongodb: WARN
    #org.springframework.messaging: DEBUG
    #org.springframework.web: DEBUG