<#import 'parts/common.ftlh' as c>
<@c.page>
    <div class="container mt-5">
        <div class="alert alert-danger text-center">
            <h1 class="display-4">403</h1>
            <p class="lead">Доступ к данной странице запрещен</p>
            <hr class="my-4">
            <p>У вас недостаточно прав для доступа к этому ресурсу.</p>
            <a class="btn btn-primary" href="http://localhost:8081/home" role="button">На главную</a>
        </div>
    </div>
</@c.page>