name: Run unit & integration tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests
        run: mvn clean test -Dtest="com/main/Jora/unit/*Test"

      - name: Save unit tests results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-results
          path: target/allure-results

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run integration tests
        run: mvn test -Dtest="com/main/Jora/integration/*Test"

      - name: Save integration tests results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-tests-results
          path: target/allure-results

  allure-report:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests ]
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Download unit tests results
        uses: actions/download-artifact@v4
        with:
          name: unit-tests-results
          path: target/allure-results

      - name: Download integration tests results
        uses: actions/download-artifact@v4
        with:
          name: integration-tests-results
          path: target/allure-results

      - name: Generate Allure Report
        run: |
          mvn allure:report
          mkdir -p public
          cp -R target/site/allure-maven-plugin/* public/
      - name: Check if Allure report is generated
        run: ls -R target/site/allure-maven-plugin
      - name: Check Allure test results
        run: ls -R target/allure-results

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4